### PR TITLE
Add opt-in go toolchain to CI extension template

### PR DESCRIPTION
**Pull request by ajzo90**
Similar to rust toolchain, it uses an opt-in flag `enable_go` to install the toolchain.

```
  duckdb-next-build:
    ...
    with:
      ...
      enable_go: true
```

This is useful for building duckdb extensions in Go. 
See example repository https://github.com/ajzo90/duckdb-go-extension-example

### CODE REVIEW

**Review by carlopi — CHANGES_REQUESTED** [review]
Thanks for the PR, can you possibly enable the go toolchain for the quack demo extension, with the goal of checking in CI at least the setup is working as intended?

Thanks

**Comment by ajzo90** [comment]
> Thanks for the PR, can you possibly enable the go toolchain for the quack demo extension, with the goal of checking in CI at least the setup is working as intended?
> 
> Thanks

I added the references to this branch and triggered CI, not sure I understand what I should do next. I don't understand the role of TestCITools.yml that you changed, but I guess it looks ok now?

The Go toolchain is just verified to work on Linux and Mac.

**Comment by carlopi** [comment]
Request for change was about adding "go" somewhere in the CI that get trigger to verify that, going forward, at least base setup keeps working.
Then I realised it was probably faster for me to add it.

I think we would also be happy to add a demo go-based extension, so it gets verified end-to-end, but that can be done later.

I think this is good to go, thanks!

**Review by carlopi — APPROVED** [review]
Thanks!!

**Comment by ajzo90** [comment]
> Request for change was about adding "go" somewhere in the CI that get trigger to verify that, going forward, at least base setup keeps working. Then I realised it was probably faster for me to add it.
> 
> I think we would also be happy to add a demo go-based extension, so it gets verified end-to-end, but that can be done later.
> 
> I think this is good to go, thanks!

Thanks!
I'm working on a concrete extension for adding xxhash functions, it should be done later today.

**Comment by carlopi** [comment]
Also do consider sending that to community extension, it would cool to have. Ping if there is else that seems off / can be improved.

**Pull request merged**
