### PR TITLE
Add support for fortran and openmp as toolchains

### PR DESCRIPTION
**Pull request by JAicewizard**
This adds support for fortran and openmp "toolchains".

The fortran "toolchain" ensures that a fortran compiler is present, and omp ensures that the compiler can use openmp.

### CODE REVIEW

**Comment by samansmink** [comment]
Hey @JAicewizard thanks for the PR! would you mind enabling the extra toolchains for the quack extension build in https://github.com/duckdb/extension-ci-tools/blob/main/.github/workflows/TestCITools.yml? that way they are run by CI at least (even though we are currently not really using them, at least we will be able to detect when the installation step fails)

**Comment by JAicewizard** [comment]
If needed I can add a test using the faiss extension, which uses both, but I don't know what your tradeoffs are for including these expensive tests

**Comment by samansmink** [comment]
yea I think just enabling the build for quack is a decent balance here

**Comment by JAicewizard** [comment]
I may have found some small issues that somehow slipped through, will update once fixed (just don't merge yet)

**Comment by JAicewizard** [comment]
Fixed a the small issue, CI seemed to have passed except for the unrelated rust build (maybe pinning this repo to a working version will avoid this?)

**Comment by samansmink** [comment]
Thanks! yea I will take a look there

**Pull request merged**
